server:
  port: ${PORT:0}

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: series-dev
      #    username: usr-series
      #    password: pwd-series
  zipkin:
    baseUrl: http://localhost:9411/
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/