server:
  port: ${PORT:0}

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: series

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/